export const PICKED_TITLES = [
  'Mr. Robot',
  'Beauty in Black',
  'Silicon Valley',
  'Game of Thrones',
  'Power Book II: Ghost',
  'Breaking Bad',
  'Better Call Saul',
  'The Wire',
  'The Sopranos',
  'Peaky Blinders',
  'Stranger Things',
  'Money Heist',
  'Squid Game',
  'The Boys',
  'The Last of Us',
  'Chernobyl',
  'Dark',
  'Black Mirror',
  'Ozark',
  'Narcos',
  'Prison Break',
  'Suits',
  'Vikings',
  'House of Cards',
  'True Detective',
  'Westworld',
  'Sherlock',
  'Dexter',
  'Fargo',
  'Euphoria',
  'Lucifer',
  'The Witcher',
  'Wednesday',
  'You',
  'Sex Education',
  'The Crown',
  'Bridgerton',
  'The Mandalorian',
  'Loki',
  'Friends',
  'The Office',
  'Brooklyn Nine-Nine',
  'Modern Family',
  'The Big Bang Theory',
  'How I Met Your Mother',
  'South Park',
  'Family Guy',
  'Rick and Morty',
  'Attack on Titan',
  'Death Note',
]
